version: '3'

services:
  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
